/*
 * Decompiled with CFR 0.152.
 */
class CEnemyPartyArray {
    private int m_nNum;
    private CEnemyParty[] m_acParty;

    public void Create() {
        this.m_nNum = 13;
        this.m_acParty = new CEnemyParty[this.m_nNum];
        int n = 1;
        this.m_acParty[0] = new CEnemyParty();
        this.m_acParty[0].m_nEnemyNum = n;
        this.m_acParty[0].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[0].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[0].m_anLoadEnemy[0].m_nKind = 1;
        this.m_acParty[0].m_anLoadEnemy[0].m_fXPos = 0.0f;
        n = 5;
        this.m_acParty[1] = new CEnemyParty();
        this.m_acParty[1].m_nEnemyNum = n;
        this.m_acParty[1].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[1].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[1].m_anLoadEnemy[0].m_nKind = 1;
        this.m_acParty[1].m_anLoadEnemy[0].m_fXPos = -400.0f;
        this.m_acParty[1].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[1].m_anLoadEnemy[1].m_nKind = 1;
        this.m_acParty[1].m_anLoadEnemy[1].m_fXPos = -200.0f;
        this.m_acParty[1].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[1].m_anLoadEnemy[2].m_nKind = 1;
        this.m_acParty[1].m_anLoadEnemy[2].m_fXPos = 0.0f;
        this.m_acParty[1].m_anLoadEnemy[3] = new CLoadBattleEnemy();
        this.m_acParty[1].m_anLoadEnemy[3].m_nKind = 1;
        this.m_acParty[1].m_anLoadEnemy[3].m_fXPos = 200.0f;
        this.m_acParty[1].m_anLoadEnemy[4] = new CLoadBattleEnemy();
        this.m_acParty[1].m_anLoadEnemy[4].m_nKind = 1;
        this.m_acParty[1].m_anLoadEnemy[4].m_fXPos = 400.0f;
        n = 2;
        this.m_acParty[2] = new CEnemyParty();
        this.m_acParty[2].m_nEnemyNum = n;
        this.m_acParty[2].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[2].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[2].m_anLoadEnemy[0].m_nKind = 2;
        this.m_acParty[2].m_anLoadEnemy[0].m_fXPos = -150.0f;
        this.m_acParty[2].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[2].m_anLoadEnemy[1].m_nKind = 2;
        this.m_acParty[2].m_anLoadEnemy[1].m_fXPos = 150.0f;
        n = 5;
        this.m_acParty[3] = new CEnemyParty();
        this.m_acParty[3].m_nEnemyNum = n;
        this.m_acParty[3].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[3].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[3].m_anLoadEnemy[0].m_nKind = 1;
        this.m_acParty[3].m_anLoadEnemy[0].m_fXPos = -360.0f;
        this.m_acParty[3].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[3].m_anLoadEnemy[1].m_nKind = 1;
        this.m_acParty[3].m_anLoadEnemy[1].m_fXPos = -180.0f;
        this.m_acParty[3].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[3].m_anLoadEnemy[2].m_nKind = 3;
        this.m_acParty[3].m_anLoadEnemy[2].m_fXPos = 0.0f;
        this.m_acParty[3].m_anLoadEnemy[3] = new CLoadBattleEnemy();
        this.m_acParty[3].m_anLoadEnemy[3].m_nKind = 1;
        this.m_acParty[3].m_anLoadEnemy[3].m_fXPos = 180.0f;
        this.m_acParty[3].m_anLoadEnemy[4] = new CLoadBattleEnemy();
        this.m_acParty[3].m_anLoadEnemy[4].m_nKind = 1;
        this.m_acParty[3].m_anLoadEnemy[4].m_fXPos = 360.0f;
        n = 4;
        this.m_acParty[4] = new CEnemyParty();
        this.m_acParty[4].m_nEnemyNum = n;
        this.m_acParty[4].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[4].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[4].m_anLoadEnemy[0].m_nKind = 4;
        this.m_acParty[4].m_anLoadEnemy[0].m_fXPos = -330.0f;
        this.m_acParty[4].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[4].m_anLoadEnemy[1].m_nKind = 4;
        this.m_acParty[4].m_anLoadEnemy[1].m_fXPos = -110.0f;
        this.m_acParty[4].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[4].m_anLoadEnemy[2].m_nKind = 4;
        this.m_acParty[4].m_anLoadEnemy[2].m_fXPos = 110.0f;
        this.m_acParty[4].m_anLoadEnemy[3] = new CLoadBattleEnemy();
        this.m_acParty[4].m_anLoadEnemy[3].m_nKind = 4;
        this.m_acParty[4].m_anLoadEnemy[3].m_fXPos = 330.0f;
        n = 4;
        this.m_acParty[5] = new CEnemyParty();
        this.m_acParty[5].m_nEnemyNum = n;
        this.m_acParty[5].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[5].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[5].m_anLoadEnemy[0].m_nKind = 2;
        this.m_acParty[5].m_anLoadEnemy[0].m_fXPos = -300.0f;
        this.m_acParty[5].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[5].m_anLoadEnemy[1].m_nKind = 3;
        this.m_acParty[5].m_anLoadEnemy[1].m_fXPos = -100.0f;
        this.m_acParty[5].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[5].m_anLoadEnemy[2].m_nKind = 3;
        this.m_acParty[5].m_anLoadEnemy[2].m_fXPos = 100.0f;
        this.m_acParty[5].m_anLoadEnemy[3] = new CLoadBattleEnemy();
        this.m_acParty[5].m_anLoadEnemy[3].m_nKind = 2;
        this.m_acParty[5].m_anLoadEnemy[3].m_fXPos = 300.0f;
        n = 3;
        this.m_acParty[6] = new CEnemyParty();
        this.m_acParty[6].m_nEnemyNum = n;
        this.m_acParty[6].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[6].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[6].m_anLoadEnemy[0].m_nKind = 3;
        this.m_acParty[6].m_anLoadEnemy[0].m_fXPos = -250.0f;
        this.m_acParty[6].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[6].m_anLoadEnemy[1].m_nKind = 3;
        this.m_acParty[6].m_anLoadEnemy[1].m_fXPos = 0.0f;
        this.m_acParty[6].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[6].m_anLoadEnemy[2].m_nKind = 3;
        this.m_acParty[6].m_anLoadEnemy[2].m_fXPos = 250.0f;
        n = 3;
        this.m_acParty[7] = new CEnemyParty();
        this.m_acParty[7].m_nEnemyNum = n;
        this.m_acParty[7].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[7].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[7].m_anLoadEnemy[0].m_nKind = 4;
        this.m_acParty[7].m_anLoadEnemy[0].m_fXPos = -250.0f;
        this.m_acParty[7].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[7].m_anLoadEnemy[1].m_nKind = 2;
        this.m_acParty[7].m_anLoadEnemy[1].m_fXPos = 0.0f;
        this.m_acParty[7].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[7].m_anLoadEnemy[2].m_nKind = 4;
        this.m_acParty[7].m_anLoadEnemy[2].m_fXPos = 250.0f;
        n = 1;
        this.m_acParty[8] = new CEnemyParty();
        this.m_acParty[8].m_nEnemyNum = n;
        this.m_acParty[8].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[8].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[8].m_anLoadEnemy[0].m_nKind = 5;
        this.m_acParty[8].m_anLoadEnemy[0].m_fXPos = 0.0f;
        n = 3;
        this.m_acParty[9] = new CEnemyParty();
        this.m_acParty[9].m_nEnemyNum = n;
        this.m_acParty[9].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[9].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[9].m_anLoadEnemy[0].m_nKind = 6;
        this.m_acParty[9].m_anLoadEnemy[0].m_fXPos = -250.0f;
        this.m_acParty[9].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[9].m_anLoadEnemy[1].m_nKind = 6;
        this.m_acParty[9].m_anLoadEnemy[1].m_fXPos = 0.0f;
        this.m_acParty[9].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[9].m_anLoadEnemy[2].m_nKind = 6;
        this.m_acParty[9].m_anLoadEnemy[2].m_fXPos = 250.0f;
        n = 4;
        this.m_acParty[10] = new CEnemyParty();
        this.m_acParty[10].m_nEnemyNum = n;
        this.m_acParty[10].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[10].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[10].m_anLoadEnemy[0].m_nKind = 8;
        this.m_acParty[10].m_anLoadEnemy[0].m_fXPos = -330.0f;
        this.m_acParty[10].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[10].m_anLoadEnemy[1].m_nKind = 8;
        this.m_acParty[10].m_anLoadEnemy[1].m_fXPos = -110.0f;
        this.m_acParty[10].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[10].m_anLoadEnemy[2].m_nKind = 8;
        this.m_acParty[10].m_anLoadEnemy[2].m_fXPos = 110.0f;
        this.m_acParty[10].m_anLoadEnemy[3] = new CLoadBattleEnemy();
        this.m_acParty[10].m_anLoadEnemy[3].m_nKind = 8;
        this.m_acParty[10].m_anLoadEnemy[3].m_fXPos = 330.0f;
        n = 3;
        this.m_acParty[11] = new CEnemyParty();
        this.m_acParty[11].m_nEnemyNum = n;
        this.m_acParty[11].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[11].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[11].m_anLoadEnemy[0].m_nKind = 8;
        this.m_acParty[11].m_anLoadEnemy[0].m_fXPos = -250.0f;
        this.m_acParty[11].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[11].m_anLoadEnemy[1].m_nKind = 6;
        this.m_acParty[11].m_anLoadEnemy[1].m_fXPos = 0.0f;
        this.m_acParty[11].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[11].m_anLoadEnemy[2].m_nKind = 8;
        this.m_acParty[11].m_anLoadEnemy[2].m_fXPos = 250.0f;
        n = 3;
        this.m_acParty[12] = new CEnemyParty();
        this.m_acParty[12].m_nEnemyNum = n;
        this.m_acParty[12].m_anLoadEnemy = new CLoadBattleEnemy[n];
        this.m_acParty[12].m_anLoadEnemy[0] = new CLoadBattleEnemy();
        this.m_acParty[12].m_anLoadEnemy[0].m_nKind = 8;
        this.m_acParty[12].m_anLoadEnemy[0].m_fXPos = -300.0f;
        this.m_acParty[12].m_anLoadEnemy[1] = new CLoadBattleEnemy();
        this.m_acParty[12].m_anLoadEnemy[1].m_nKind = 5;
        this.m_acParty[12].m_anLoadEnemy[1].m_fXPos = 0.0f;
        this.m_acParty[12].m_anLoadEnemy[2] = new CLoadBattleEnemy();
        this.m_acParty[12].m_anLoadEnemy[2].m_nKind = 8;
        this.m_acParty[12].m_anLoadEnemy[2].m_fXPos = 300.0f;
    }

    public CEnemyParty Get(int n) {
        return this.m_acParty[n];
    }

    public int GetLength() {
        return this.m_nNum;
    }

    CEnemyPartyArray() {
        this.Create();
    }
}

